# ============================
# API Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2-deploy
  namespace: demo
  labels:
    app: api
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: v2
  template:
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
        - name: api
          image: orlando/api:1.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVER_PORT
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-app-password

# ============================
# Frontend Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: demo
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: orlando/frontend:1.0.1
          ports:
            - containerPort: 80

# ============================
# MySQL Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: demo
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: orlando/mysql:1.0.1
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-app-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}   # temporal (en producción: PVC)

# ============================
# Gateway (Traefik) Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  namespace: demo
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: traefik
          image: orlando/gateway:1.0.1
          ports:
            - containerPort: 8080

# ============================
# Prometheus Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  namespace: demo
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: orlando/prometheus:1.0.1
          ports:
            - containerPort: 9090

