apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  namespace: demo
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080

apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: demo
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30090
